apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  labels:
    app: pod-test
spec:
  containers:
    - name: pod-test
      image: 192.168.0.195:5000/nginx:joo
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pod-test-service
spec:
  selector:
    app: pod-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort

